# Generated by Django 5.0.4 on 2024-05-06 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pemasukan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_Pemasukan', models.CharField(max_length=100)),
                ('pemasukan_gaji', models.CharField(max_length=10, unique=True)),
                ('pendapatan_lainnya', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
