# Generated by Django 5.0.4 on 2024-05-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemasukan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengeluaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_Pengeluaran', models.CharField(max_length=100)),
                ('belanja_bulanan', models.CharField(max_length=10, unique=True)),
                ('tagihan', models.CharField(max_length=10, unique=True)),
                ('pembelian_lainnya', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
