# Generated by Django 5.0.4 on 2024-05-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemasukan', '0002_pengeluaran'),
    ]

    operations = [
        migrations.CreateModel(
            name='laporankeuangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pemasukan', models.CharField(max_length=100)),
                ('total_pengeluaran', models.CharField(max_length=10, unique=True)),
                ('saldo_akhir', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
