# Generated by Django 5.0.4 on 2024-05-11 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemasukan', '0003_laporankeuangan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengeluaran',
            name='Pemasukan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Pengeluaran', to='pemasukan.pemasukan'),
            preserve_default=False,
        ),
    ]
